check:
  global:
    statements: 53
    lines: 53
    branches: 33
    functions: 50
    excludes: []
    each:
      statements: 0
      lines: 0
      branches: 0
      functions: 0
      excludes: []
