language: node_js
node_js:
  - "node"
addons:
  code_climate:
    repo_token: 9c6558805c8a00ef83371f4dcd82bfc765d2eac147a7442164f8cc1b401d43de
after_success:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < ./coverage/lcov.info
